#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# MoniMac release setup (ticket 20). Run it from anywhere: scripts/release/setup-wizard.sh
# Every outward-facing command (gh secret set, git push, tags) is shown first and runs only after you confirm.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
REPO_URL="https://github.com/lethanhvietctt5/moni-mac"
IDENTITY_NAME="MoniMac Self-Signed"
SPARKLE_BIN="$ROOT/build/release/SourcePackages/artifacts/sparkle/Sparkle/bin"
PLACEHOLDER="PLACEHOLDER_SPARKLE_PUBLIC_ED_KEY"
WORK="$(mktemp -d)"   # the exported EdDSA private key lives here only while the wizard runs
trap 'rm -rf "$WORK"' EXIT
SPARKLE_KEY_FILE="$WORK/sparkle-private-key"
ENV_FILE="$WORK/unused.env" # nothing here belongs in a .env: secrets go to GitHub only

# skip_if_done "question" — on re-runs, lets the maintainer skip a stage already finished.
skip_if_done() { confirm "$1 Skip this stage?"; }

# run "command" — show a command, run it only after a yes.
run() {
  printf '  %s$ %s%s\n' "$BOLD" "$1" "$RESET"
  if confirm "Run it now?"; then bash -c "$1"; else warn "not run — run it yourself before continuing"; pause; fi
}

wait_for_release() {
  open_url "$REPO_URL/actions/workflows/release.yml"
  say "Wait for the Release run for $1 to finish (about 10 minutes). If it fails, read the failing step's log;"
  say "the scripts it runs are in scripts/release/, and 'make-release.sh $1 --dry-run' reproduces most of it locally."
  pause "Press Enter when the run is green."
}

banner "MoniMac — release signing, update key, and first releases"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Check tools"
say "You need: Xcode, XcodeGen (brew install xcodegen), and the GitHub CLI logged in to this repo."
command -v xcodebuild >/dev/null && step "xcodebuild ✓" || warn "xcodebuild missing: install Xcode"
command -v xcodegen >/dev/null && step "xcodegen ✓" || warn "xcodegen missing: brew install xcodegen"
if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then step "gh ✓ (logged in)"; else warn "gh missing or logged out: brew install gh && gh auth login"; fi
[ -z "$(git status --porcelain)" ] && step "git working tree clean ✓" || warn "uncommitted changes: commit or stash them first"
[ "$(git branch --show-current)" = main ] && step "on main ✓" || warn "you're on $(git branch --show-current); releases are tagged from main"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Stable signing identity"
say "Releases are signed with one self-signed certificate forever. macOS ties granted permissions"
say "(notifications, audio capture, location) to it, so they survive updates. Lose it and every user"
say "is asked again; that's why stage 3 makes a backup."
if security find-certificate -c "$IDENTITY_NAME" >/dev/null 2>&1; then
  step "\"$IDENTITY_NAME\" is already in your login keychain ✓"
else
  say "This creates it in your login keychain. macOS asks for your password to trust it for code signing."
  run "scripts/create-signing-cert.sh"
fi
say "Sign your own builds with it too (Config/Local.xcconfig is gitignored):"
if grep -qs "^CODE_SIGN_IDENTITY *= *$IDENTITY_NAME" Config/Local.xcconfig; then
  step "Config/Local.xcconfig already uses it ✓"
elif confirm "Set CODE_SIGN_IDENTITY = $IDENTITY_NAME in Config/Local.xcconfig?"; then
  touch Config/Local.xcconfig
  grep -v '^CODE_SIGN_IDENTITY' Config/Local.xcconfig >"$WORK/local.xcconfig" || true
  echo "CODE_SIGN_IDENTITY = $IDENTITY_NAME" >>"$WORK/local.xcconfig"
  mv "$WORK/local.xcconfig" Config/Local.xcconfig
  step "wrote Config/Local.xcconfig ✓"
fi
note "On the first build with it, macOS asks whether codesign may use the key: choose \"Always Allow\"."
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Export the identity as a .p12"
say "CI signs with a copy of the identity. Export only this one identity from Keychain Access"
say "(not 'security export', which exports every identity in the keychain)."
open -a "Keychain Access" 2>/dev/null || warn "open Keychain Access yourself (Spotlight: Keychain Access)"
step "Select the login keychain › My Certificates."
step "Right-click \"$IDENTITY_NAME\" (expand it: the private key must be under it) › Export \"$IDENTITY_NAME\"…"
step "File Format: Personal Information Exchange (.p12). Save it as ~/Desktop/MoniMac-Self-Signed.p12."
step "Choose a strong export password and keep it: it's a GitHub secret in stage 5."
step "Keep a copy of the .p12 and its password in your password manager. It is the release identity's only backup."
pause "Press Enter once the .p12 is saved."
ask P12_PATH "Path to the .p12 [~/Desktop/MoniMac-Self-Signed.p12]:"
P12_PATH="${P12_PATH:-$HOME/Desktop/MoniMac-Self-Signed.p12}"
P12_PATH="${P12_PATH/#\~/$HOME}"
[ -f "$P12_PATH" ] || { warn "no file at $P12_PATH"; exit 1; }
ask_secret P12_PASSWORD "The .p12's export password (hidden):"
if P12_PASSWORD="$P12_PASSWORD" /usr/bin/openssl pkcs12 -in "$P12_PATH" -nokeys -passin env:P12_PASSWORD 2>/dev/null \
    | /usr/bin/openssl x509 -noout -subject 2>/dev/null | grep -q "$IDENTITY_NAME"; then
  step "the .p12 opens with that password and holds \"$IDENTITY_NAME\" ✓"
else
  warn "couldn't confirm the .p12 with openssl (wrong password, or an algorithm LibreSSL can't read)."
  confirm "Continue anyway?" || exit 1
fi

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Sparkle EdDSA update key"
say "Sparkle verifies every update archive with this key pair. The public half goes into the app"
say "(stage 6); the private half signs releases in CI (stage 5) and stays in your login keychain."
if [ ! -x "$SPARKLE_BIN/generate_keys" ]; then
  say "Sparkle's tools come with its Swift package. Resolving it (no build):"
  run "xcodegen generate --quiet && xcodebuild -resolvePackageDependencies -project MoniMac.xcodeproj -scheme MoniMac -derivedDataPath build/release"
fi
[ -x "$SPARKLE_BIN/generate_keys" ] || { warn "Sparkle's generate_keys is still missing at $SPARKLE_BIN"; exit 1; }
if PUBLIC_KEY="$("$SPARKLE_BIN/generate_keys" -p 2>/dev/null)" && [ -n "$PUBLIC_KEY" ]; then
  step "a Sparkle key already exists in your login keychain ✓"
else
  say "generate_keys creates the pair and saves the private key in your login keychain."
  run "\"$SPARKLE_BIN/generate_keys\""
  PUBLIC_KEY="$("$SPARKLE_BIN/generate_keys" -p)"
fi
step "Public key: $PUBLIC_KEY"
say "Exporting the private key to a temporary file, deleted when this wizard exits:"
"$SPARKLE_BIN/generate_keys" -x "$SPARKLE_KEY_FILE" >/dev/null
[ -s "$SPARKLE_KEY_FILE" ] && step "exported ✓" || { warn "export failed"; exit 1; }
note "Back up the private key too: Keychain Access › login › Passwords › \"Private key for signing Sparkle updates\"."
note "Without it, installed copies of MoniMac can never be updated again."
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "GitHub secrets"
say "The release workflow (.github/workflows/release.yml) reads three secrets:"
step "MONIMAC_CERT_P12        the .p12, base64"
step "MONIMAC_CERT_PASSWORD   its export password"
step "SPARKLE_ED_PRIVATE_KEY  the exported EdDSA private key"
say "Each is sent with 'gh secret set <name>' on standard input, never on the command line."
if confirm "Set all three secrets on $(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo 'this repo') now?"; then
  set_secret MONIMAC_CERT_P12 "$(base64 -i "$P12_PATH")"
  set_secret MONIMAC_CERT_PASSWORD "$P12_PASSWORD"
  set_secret SPARKLE_ED_PRIVATE_KEY "$(cat "$SPARKLE_KEY_FILE")"
  gh secret list 2>/dev/null | sed 's/^/    /' || true
else
  warn "skipped: set them yourself before tagging"
  SKIPPED+=("GitHub secrets MONIMAC_CERT_P12, MONIMAC_CERT_PASSWORD, SPARKLE_ED_PRIVATE_KEY")
fi
if confirm "Delete $P12_PATH now (you kept a copy in your password manager)?"; then rm "$P12_PATH" && step "deleted ✓"; fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Put the public key in the app"
if ! grep -q "$PLACEHOLDER" project.yml; then
  step "project.yml no longer has the placeholder ✓ ($(grep 'SUPublicEDKey:' project.yml | xargs))"
else
  say "Replacing $PLACEHOLDER in project.yml with $PUBLIC_KEY and regenerating App/Info.plist."
  if confirm "Edit project.yml?"; then
    sed -i '' "s|$PLACEHOLDER|$PUBLIC_KEY|" project.yml
    xcodegen generate --quiet
    git --no-pager diff --stat
  fi
fi
say "Optional, about 3 minutes: a local dry run with the real key proves the private key in the secret"
say "matches this public key (ad-hoc signed, nothing is published)."
if [ -s "$SPARKLE_KEY_FILE" ] && confirm "Run the dry run?"; then
  SPARKLE_ED_PRIVATE_KEY="$(cat "$SPARKLE_KEY_FILE")" DRY_RUN_PUBLIC_KEY="$PUBLIC_KEY" \
    scripts/release/make-release.sh v0.1.0 --dry-run | tail -6 || warn "the dry run failed; fix it before tagging"
fi
say "Commit it through a pull request, as every change to main:"
run "git switch -c chore/sparkle-public-key && git commit -m 'Sparkle public update key' project.yml App/Info.plist && git push -u origin HEAD && gh pr create --fill"
pause "Merge the pull request on GitHub, then press Enter."
run "git switch main && git pull --ff-only"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "First release: v0.1.0"
if gh release view v0.1.0 >/dev/null 2>&1; then
  step "v0.1.0 is already released ✓"
else
  say "Pushing a v* tag starts the Release workflow, which builds, signs, and publishes the release."
  run "git tag v0.1.0 && git push origin v0.1.0"
  wait_for_release v0.1.0
fi

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Check the release"
check() { if eval "$2"; then step "$1 ✓"; else warn "$1 ✗"; fi; }
ASSETS="$(gh release view v0.1.0 --json assets -q '.assets[].name' 2>/dev/null || true)"
check "the release has MoniMac-0.1.0.zip" "grep -qx MoniMac-0.1.0.zip <<<\"\$ASSETS\""
check "the release has appcast.xml" "grep -qx appcast.xml <<<\"\$ASSETS\""
FEED="$(curl -fsSL "$REPO_URL/releases/latest/download/appcast.xml" || true)"
check "the feed URL in the app serves the appcast" "grep -q '<sparkle:shortVersionString>0.1.0<' <<<\"\$FEED\""
check "the appcast item is signed" "grep -q 'sparkle:edSignature=' <<<\"\$FEED\""
open_url "$REPO_URL/releases/tag/v0.1.0"
step "Read the release notes: they should carry the install steps."
pause

# ── 9 ────────────────────────────────────────────────────────────────────
stage "Install like a user, and take the README screenshots"
say "Use the release, not a local build. If a local MoniMac is running, quit it first."
step "Download MoniMac-0.1.0.zip from the release page (in Safari or Chrome, so it's quarantined like a user's)."
step "Open the zip, drag MoniMac into Applications, and open it."
step "macOS blocks it. Screenshot that dialog: ⌘⇧4, Space, click the dialog."
step "  Save as docs/images/install-blocked.png, then click Done."
step "Open System Settings › Privacy & Security, scroll to Security. Screenshot the window with"
step "  \"MoniMac was blocked…\" and Open Anyway: save as docs/images/install-open-anyway.png."
step "Click Open Anyway, confirm, and enter your password. MoniMac opens."
step "Grant a permission: open MoniMac's window › Network tab and allow Location (for the Wi-Fi name)."
step "Check: System Settings › Privacy & Security › Location Services lists MoniMac, on."
pause "Press Enter when MoniMac is running with Location allowed."
say "For the record (the update must not change these):"
codesign -d -r- /Applications/MoniMac.app 2>&1 | grep designated | sed 's/^/    /' || true
xattr -p com.apple.quarantine /Applications/MoniMac.app >/dev/null 2>&1 \
  && note "the installed app carries a quarantine flag (expected after a browser download)" \
  || note "the installed app has no quarantine flag"
say "In README.md, replace the two \"Screenshot placeholder\" blocks under Install with:"
note '  ![macOS blocks MoniMac on first launch](docs/images/install-blocked.png)'
note '  ![Open Anyway in System Settings › Privacy & Security](docs/images/install-open-anyway.png)'
say "and commit both images with it, through a pull request. Later releases add them to their notes automatically."
pause

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Update path: v0.1.1"
say "This checks ticket 20's remaining criteria: the installed v0.1.0 finds and installs an update,"
say "the updated app opens without Gatekeeper, and the Location permission survives."
if ! gh release view v0.1.1 >/dev/null 2>&1; then
  note "Tag after the README screenshots are merged, so v0.1.1 has a change to list."
  run "git switch main && git pull --ff-only && git tag v0.1.1 && git push origin v0.1.1"
  wait_for_release v0.1.1
fi
step "In the installed MoniMac 0.1.0: Settings › Data & About › Check for Updates…"
note "  (On its second launch Sparkle also asks whether to check automatically; either answer is fine.)"
step "Sparkle offers 0.1.1: Install Update, then Install and Relaunch."
pause "Press Enter when MoniMac has relaunched."
check "the installed app is 0.1.1" "[ \"\$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" /Applications/MoniMac.app/Contents/Info.plist 2>/dev/null)\" = 0.1.1 ]"
check "the update carries no quarantine flag" "! xattr -p com.apple.quarantine /Applications/MoniMac.app >/dev/null 2>&1"
say "Designated requirement now (must match the one in stage 9):"
codesign -d -r- /Applications/MoniMac.app 2>&1 | grep designated | sed 's/^/    /' || true
confirm "Did the updated MoniMac open WITHOUT a Gatekeeper prompt?" && G=yes || G=no
confirm "Does its Network tab show the Wi-Fi name without asking for Location again?" && P=yes || P=no
say "Results for docs/tickets/monimac-v1/20-release-pipeline.md:"
step "Tag → signed build and feed entry: $(gh release view v0.1.1 >/dev/null 2>&1 && echo yes || echo no)"
step "Installed build detects and installs the update: $( [ "$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" /Applications/MoniMac.app/Contents/Info.plist 2>/dev/null)" = 0.1.1 ] && echo yes || echo no)"
step "Updated app opens without Gatekeeper: $G"
step "Permissions survive the update: $P"
if [ "$G" = no ]; then
  warn "Gatekeeper prompted after the update. The spec's fallback applies: make \"Update available\" link to"
  warn "the release page instead of installing in place. Note the macOS version and open an issue."
fi
pause

finish
note "Back up: the .p12 and its password, and the Sparkle private key, in your password manager."
note "Next releases: merge to main, then 'git tag vX.Y.Z && git push origin vX.Y.Z'."
